/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anyjava' at '15. 11. 20 오후 1:00' with Gradle 2.8
 *
 * @author anyjava, @date 15. 11. 20 오후 1:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
